# 应用服务 WEB 访问端口
server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: huamulan0158
    url: jdbc:mysql://8.134.32.45:13306/poi_db?serverTimezone=GMT%2B8&characterEncoding=utf8&&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource

# 配置 mp
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

excel:
  pool:
    max-pool-size: 3
    core-pool-size: 3
    keep-alive-time: 0
    max-queue-size: 10
    name-prefix: excel